spring:
  application:
    name: wordbattle_backend

  datasource:
    url: jdbc:postgresql://localhost:5432/wordbattle
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 10000
      pool-name: HikariCP

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1023646983433-rjcan6j1hgois0p8kd61nv7gfjm229ug.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/api/v1/oauth2/callback/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: -1
    display-request-duration: true

cors:
  allowed-origin-ip: http://localhost:3000